export const types = {

  AUTH_START: "AUTH_START",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILD: "AUTH_FAILD",

  SIGN_OUT: "SIGN_OUT",

  GET_GALLERY_IMAGES_START: "GET_GALLERY_IMAGES_START",
  GET_GALLERY_IMAGES_SUCCESS: "GET_GALLERY_IMAGES_SUCCESS",
  GET_GALLERY_IMAGES_FAILED: "GET_GALLERY_IMAGES_FAILED",

  GET_GALLERY_IMAGES_FOR_ADMIN_START: "GET_GALLERY_IMAGES_FOR_ADMIN_START",
  GET_GALLERY_IMAGES_FOR_ADMIN_SUCCESS: "GET_GALLERY_IMAGES_FOR_ADMIN_SUCCESS",
  GET_GALLERY_IMAGES_FOR_ADMIN_FAILED: "GET_GALLERY_IMAGES_FOR_ADMIN_FAILED",
};







